controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
actualite_politique:
    path: /actualite-politique
    controller: App\Controller\ActualitePolitiqueController::index
